# Generated by Django 6.0.1 on 2026-01-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='many_to_many',
            field=models.ManyToManyField(related_name='Many_to_many', to='blog.post'),
        ),
    ]
